services:
  - type: web
    name: text-to-speech-api
    env: node
    plan: free
    region: Frankfurt
    autoDeploy: true
    buildCommand: 'npm install'
    startCommand: 'node index.js'
    envVars:
      # Variables API (à remplacer par tes clés)
      - key: GEMINI_API_KEY
        sync: false
      - key: ELEVEN_LABS_API_KEY
        sync: false

      # Variables voix
      - key: GEMINI_VOICE
        value: "Kore"
      - key: ELEVEN_LABS_VOICE
        sync: false

      # Domaine autorisé pour CORS
      - key: DOMAIN_AUTORISE
        sync: false
